### ISSUE TITLE
Error while generating FBA for GHGI table A-18

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#192]
> `Traceback (most recent call last):
  File "w:\Air Emissions Physical Flows Account\Code\GHGbyindustrydocs\flowsa_FBS\generateExternalFlowBySector.py", line 28, in <module>
    flowsa.flowbysector.main(method=method, fbsconfigpath=fbsMethodPath)
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\flowbysector.py", line 299, in main
    fbs = dataset_allocation_method(
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\fbs_allocation.py", line 117, in dataset_allocation_method
    load_map_clean_fba(method, attr,
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\fbs_allocation.py", line 482, in load_map_clean_fba
    fba = load_fba_w_standardized_units(datasource=fba_sourcename,
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\flowbyfunctions.py", line 782, in load_fba_w_standardized_units
    fba = flowsa.getFlowByActivity(
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\__init__.py", line 66, in getFlowByActivity
    flowsa.flowbyactivity.main(year=year, source=datasource)
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\flowbyactivity.py", line 231, in main
    dfs = parse_data(df_list=df_list,
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\flowbyactivity.py", line 142, in parse_data
    df = dynamically_import_fxn(
  File "\\serv02cl\ODResearch\Chambers\Air Emissions Physical Flows Account\Code\flowsa-main\flowsa\data_source_scripts\EPA_GHGI.py", line 353, in ghg_parse
    acb = row['ActivityConsumedBy'].strip()
AttributeError: 'float' object has no attribute 'strip'`

This is the traceback I get when I try to run method `m1` of `GHGbyindustrydocs` on the `electricity` branch, using `flowsa` on the `develop` branch. I get the same error if I try to generate the `EPA_GHGI` FBAs directly.

**Comment by bl-young** [comment]
There is a problem with `EPA_GHGI_T_A_18` (a table only available in 2012).

When trying to run `m1`, it's looking for `EPA_GHGI_T_A_79` 2012 as an allocation source. If you don't have it locally it will try to generate all GHGI tables for 2012, hence the error.

Are you able to generate the FBAs for years besides 2012? This table is the only one I've found so far causing this error.

**Comment by bl-young** [comment]
I will look into what's going wrong with the parsing of A-18, in the meantime you can remove it from `EPA_GHGI.yaml` if you want to run `m1`. The FBS will be fine without A-18.

**Comment by matthewlchambers** [comment]
Sounds good. I've been able to generate other FBAs, so I'll remove it from `EPA_GHGI.yaml` and try that. Thanks!

**Comment by bl-young** [comment]
A-18 csv file has an extra blank row not present in the other annex tables which was causing this error

**Comment by bl-young** [comment]
@matthewlchambers if you can confirm this works on your end we can close this issue

**Comment by matthewlchambers** [comment]
Works great! Thanks!
